build: false

branches:
  only:
    - master

platform:
  - x64

image:
  - Visual Studio 2017
  - Visual Studio 2015

environment:
  matrix:
    - MINICONDA: C:\myname-conda

init:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set RUN_EXAMPLES="false"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" set RUN_EXAMPLES="true"
  - "ECHO %MINICONDA%"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCARGUMENT=%PLATFORM%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - echo "%VCVARPATH% %VCARGUMENT%"
  - "%VCVARPATH% %VCARGUMENT%"
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\myname-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  # Set environment using Conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -c conda-forge mamba
  - >-
    mamba install -c conda-forge
    cmake
    xtensor
    python
    numpy
    pyxtensor
    catch2
    highfive
  # Build/install the library
  - cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%MINICONDA%\\LIBRARY -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DSIMD=OFF .
  - nmake
  - nmake install
  - python setup.py build
  - python setup.py install

build_script:
  # Run tests
  - .\test\main
  # Run C++ examples
  - if("%RUN_EXMAPLES" -eq "true"){cd docs\examples}
  - if("%RUN_EXMAPLES" -eq "true"){.\S2}
  - if("%RUN_EXMAPLES" -eq "true"){.\S2_autocorrelation}
  - if("%RUN_EXMAPLES" -eq "true"){.\S2_mask}
  - if("%RUN_EXMAPLES" -eq "true"){.\S2_ensemble}
  - if("%RUN_EXMAPLES" -eq "true"){.\C2}
  - if("%RUN_EXMAPLES" -eq "true"){.\L}
  - if("%RUN_EXMAPLES" -eq "true"){.\W2}
  - if("%RUN_EXMAPLES" -eq "true"){.\W2c}
  - if("%RUN_EXMAPLES" -eq "true"){.\clusters}
  - if("%RUN_EXMAPLES" -eq "true"){.\clusters_centers}
  - if("%RUN_EXMAPLES" -eq "true"){.\clusters_dilate}
  - if("%RUN_EXMAPLES" -eq "true"){.\heightheight}
  - if("%RUN_EXMAPLES" -eq "true"){.\mean}
  - if("%RUN_EXMAPLES" -eq "true"){cd ..\..}
  # Run Python examples
  - if("%RUN_EXMAPLES" -eq "true"){cd docs\examples}
  - if("%RUN_EXMAPLES" -eq "true"){python S2.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python S2_autocorrelation.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python S2_mask.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python S2_ensemble.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python C2.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python L.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python W2.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python W2c.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python clusters.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python clusters_centers.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python clusters_dilate.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python clusters_dilate_periodic.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python heightheight.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){python mean.py --check}
  - if("%RUN_EXMAPLES" -eq "true"){cd ..\..}
