build: false

branches:
  only:
    - master

platform:
  - x64

image:
  - Visual Studio 2017

environment:
  matrix:
    - MINICONDA: C:\myname-conda

init:
  - "ECHO %MINICONDA%"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - echo "%VCVARPATH% %VCARGUMENT%"
  - "%VCVARPATH% %VCARGUMENT%"
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\myname-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  # Set environment using Conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -c conda-forge mamba
  - >-
    mamba install -c conda-forge
    cmake
    xtensor
    python
    numpy
    pyxtensor
    catch2
    highfive
  # Build/install the library
  - python setup.py build
  - python setup.py install
  - cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%MINICONDA%\\LIBRARY -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTS=ON -DBUILD_EXAMPLES=OFF -DSIMD=OFF -DWARNINGS=OFF .
  - nmake
  - nmake install

build_script:
  # Run tests
  - .\test\main
  # # Run C++ examples
  # - cd docs\examples
  # - .\S2
  # - .\S2_autocorrelation
  # - .\S2_mask
  # - .\S2_ensemble
  # - .\C2
  # - .\L
  # - .\W2
  # - .\W2c
  # - .\clusters
  # - .\clusters_centers
  # - .\clusters_dilate
  # - .\heightheight
  # - .\mean
  # - cd ..\..
  # # Run Python examples
  # - cd docs\examples
  # - python S2.py --check
  # - python S2_autocorrelation.py --check
  # - python S2_mask.py --check
  # - python S2_ensemble.py --check
  # - python C2.py --check
  # - python L.py --check
  # - python W2.py --check
  # - python W2c.py --check
  # - python clusters.py --check
  # - python clusters_centers.py --check
  # - python clusters_dilate.py --check
  # - python clusters_dilate_periodic.py --check
  # - python heightheight.py --check
  # - python mean.py --check
  # - python pixel_path.py --check
  # - cd ..\..
