language: cpp
dist: xenial
env:
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=gcc GCC=5 RUN_EXAMLES="false" USE_XSIMD=1
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=gcc GCC=6 RUN_EXAMLES="false" USE_XSIMD=1
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=gcc GCC=7 RUN_EXAMLES="true" USE_XSIMD=1
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env: COMPILER=clang CLANG=6.0 RUN_EXAMLES="false" USE_XSIMD=1
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: RUN_EXAMLES="true" USE_XSIMD=1
env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
before_install:
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$COMPILER" == "gcc" ]]; then
          export CXX=g++-$GCC CC=gcc-$GCC;
        fi
        if [[ "$COMPILER" == "clang" ]]; then
          export CXX=clang++-$CLANG CC=clang-$CLANG;
        fi
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CXX=clang++ CC=clang;
      fi
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cat /proc/cpuinfo;
        ldd --version;
      fi
    # Set environment using Conda
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install -c conda-forge mamba
    - >-
      mamba install -c conda-forge
      cmake
      xsimd
      xtensor
      python
      numpy
      pyxtensor
      catch2
      highfive
      h5py
      docopt
    # Build/install the library
    - cmake . -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DSIMD=${USE_XSIMD}
    - make
    - sudo make install
    - python setup.py build
    - python setup.py install
script:
    # Run tests
    - ./test/main
    # Run C++ examples
    - if [ "$RUN_EXAMPLES" = "true" ]; then cd docs/examples; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./S2; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./S2_autocorrelation; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./S2_mask; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./S2_ensemble; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./C2; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./L; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./W2; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./W2c; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./clusters; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./clusters_centers; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./clusters_dilate; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./heightheight; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then ./mean; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then cd ../..; fi
    # Run Python examples
    - if [ "$RUN_EXAMPLES" = "true" ]; then cd docs/examples; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python S2.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python S2_autocorrelation.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python S2_mask.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python S2_ensemble.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python C2.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python L.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python W2.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python W2c.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python clusters.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python clusters_centers.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python clusters_dilate.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python clusters_dilate_periodic.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python heightheight.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python mean.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then python pixel_path.py --check; fi
    - if [ "$RUN_EXAMPLES" = "true" ]; then cd ../..; fi
