language: cpp
dist: xenial
env:
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=gcc GCC=5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=gcc GCC=6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=gcc GCC=7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env: COMPILER=clang CLANG=6.0
    - os: osx
      osx_image: xcode8
      compiler: clang
env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
before_install:
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$COMPILER" == "gcc" ]]; then
          export CXX=g++-$GCC CC=gcc-$GCC;
        fi
        if [[ "$COMPILER" == "clang" ]]; then
          export CXX=clang++-$CLANG CC=clang-$CLANG;
        fi
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CXX=clang++ CC=clang;
      fi
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cat /proc/cpuinfo;
        ldd --version;
      fi
    # Set environment using Conda
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install -c conda-forge cmake
    - conda install -c conda-forge xsimd
    - conda install -c conda-forge xtensor
    - conda install -c conda-forge python
    - conda install -c conda-forge numpy
    - conda install -c conda-forge pyxtensor
    - conda install -c conda-forge catch2
    # Build/install the library
    - cmake . -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
    - make
    - sudo make install
    - python setup.py build
    - python setup.py install
script:
    # Run tests
    - ./test/main
    # Run C++ examples
    - ./docs/examples/S2
    - ./docs/examples/S2_autocorrelation
    - ./docs/examples/S2_mask
    - ./docs/examples/S2_ensemble
    - ./docs/examples/C2
    - ./docs/examples/L
    - ./docs/examples/W2
    - ./docs/examples/W2c
    - ./docs/examples/clusters
    - ./docs/examples/clusters_centers
    - ./docs/examples/clusters_dilate
    - ./docs/examples/heightheight
    - ./docs/examples/mean
    # Run Python examples
    - python docs/examples/S2.py --no-plot
    - python docs/examples/S2_autocorrelation.py --no-plot
    - python docs/examples/S2_mask.py --no-plot
    - python docs/examples/S2_ensemble.py --no-plot
    - python docs/examples/C2.py --no-plot
    - python docs/examples/L.py --no-plot
    - python docs/examples/W2.py --no-plot
    - python docs/examples/W2c.py --no-plot
    - python docs/examples/clusters.py --no-plot
    - python docs/examples/clusters_centers.py --no-plot
    - python docs/examples/clusters_dilate.py --no-plot
    - python docs/examples/heightheight.py --no-plot
    - python docs/examples/mean.py --no-plot
