channels:
- conda-forge
dependencies:
- catch2
- cmake
- docopt
- doxygen
- enstat >=0.9.7
- h5py
- highfive
- ninja
- numpy
- pybind11
- python
- scikit-build
- setuptools_scm
- xsimd
- xtensor
- xtensor-python
