channels:
- conda-forge
dependencies:
- catch2
- cmake
- doxygen
- enstat >=0.9.7
- furo
- h5py
- highfive
- ninja
- numpy
- prrng
- pybind11
- pytest
- python
- python-cppcolormap
- python-prrng
- scikit-build
- scipy
- setuptools_scm
- xsimd
- xtensor
- xtensor-python
