[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=42",
  "scikit-build>=0.13",
  "cmake>=3.18",
  "setuptools_scm[toml]>=3.4",
  "ninja",
  "enstat>=0.9.7",
  "numpy"
]

[tool.setuptools_scm]
write_to = "python/GooseEYE/_version.py"
